#!/usr/bin/env php
<?php
//TinCan interpereter v1.2 (modified for use on TIO)
$stack = array();
$vars = array();
$executed = array();
$list = array_fill(0, 90, 0);
$filename = $argv[1];

//Read file into array
$instructionarray = file($filename, FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES);
$executed = $instructionarray;

//Strip all non 40-length lines and lines not surrounded by hashes
foreach($instructionarray as $key => &$instruction){
	if(strlen($instruction) != 40){
		unset($instructionarray[$key]);
		unset($executed[$key]);
	}
	if((substr($instruction, 0, 1) != '#') or (substr($instruction, -1, 1) != '#')){
		unset($instructionarray[$key]);
		unset($executed[$key]);
	}
	$instruction = str_replace('#', '', $instruction);
	$instruction = str_replace(' ', '', $instruction);
}

//Check to make sure there are still instructions left to run
if(count($instructionarray) == 0){
	error_log("ERROR: There must be at least a single valid instruction.");
	exit(1);
}
$instructionarray = array_values($instructionarray);

//Execute program
$i = 0;
$j = 0;
while($i < count($instructionarray)){
	$line = $instructionarray[$i];
	$args = explode(',', $line);

	if(count($args) != 3){
		error_log("ERROR: Line $i has the wrong number of arguments.");
		exit(1);
	}

	foreach($args as $key => $arg){
		$vars[$key] = $arg;
		if(!is_numeric($arg)){
			$ord = ord($arg);
			if($arg == '$'){
				$vars[$key] = $i;
			}
			elseif($arg == '@'){
				$vars[$key] = $j;
			}
			elseif($arg == '&'){
				$vars[$key] = $i+1;
			}
			elseif(($ord >= 65) and ($ord <= 90)){
				$vars[$key] = '%'.$ord;
			}
			else{
				error_log("ERROR: Argument $key on line $i is not numeric.");
				exit(1);
			}
		}
	}

	if(substr($vars[0], 0, 1) == '%'){
		$vars[0] = $list[substr($vars[0], 1)];
	}
	if(substr($vars[1], 0, 1) == '%'){
		$store = substr($vars[1], 1);
		$vars[1] = $list[$store];
	}
	else{
		error_log("ERROR: Argument $key on line $i is not a storable location.");
		exit(1);
	}
	if(substr($vars[2], 0, 1) == '%'){
		$vars[2] = $list[substr($vars[2], 1)];
	}
	$list[$store] = $vars[1] - $vars[0];
	if($list[$store] <= 0){
		if($vars[2] > -1){
			$i = $vars[2]-1;
		}
	}
	if($vars[2] == -1){
		array_push($stack, $list[$store]);
	}

	$i++;
	$j++;
}
foreach($stack as $value){
	echo chr($value);
}
?>
